In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
# ExtraQ 1: From question 34,Extract individual 1D slices from main array and then combine them to form a 2D array 
#using numpy.ix_() function
a= np.arange(1,31).reshape((6, 5))
print(a)
y= c[np.ix_([0,2],[1,3])]
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 2  4]
 [12 14]]


In [4]:
#ExtraQ 2:From question 34,Find the array slicing to get the elements with values 3,8,13,18,23,28
#using Ellipsis
a = np.arange(1,31).reshape((6, 5))
print(a)
print(a[Ellipsis,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[ 3  8 13 18 23 28]


In [11]:
#ExtraQ 4:From question 34,with condition element value less than 6 ,print as -1 else as 99
#np where()
a = np.arange(1,31).reshape((6, 5))
print(a)
print(np.where(a < 6, -1, 99))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[-1 -1 -1 -1 -1]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [14]:
#ExtraQ 3:From question 34,print the truncated array with 2 elements on the edge
#using edgeitems
a= np.arange(1,31).reshape((6, 5))
np.set_printoptions(edgeitems = 2)
print()