In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [27]:
#52 Retrieve the row with minimum DBP using sorting technique.
df= pd.read_excel("HospitalDatabase .xlsx",sheet_name="AmbulatoryVisits")

dbp=df.sort_values("BloodPressureDiastolic")
dbp.head(1)


VisitID  PatientMRN  ProviderID DateofVisit           DateScheduled  \
757      163         801          11  2019-02-08 2019-02-07 23:41:12.181   

     VisitDepartmentID  VisitType  BloodPressureSystolic  \
757                  7  Follow Up                  120.0   

     BloodPressureDiastolic      Pulse VisitStatus  
757               51.695653  53.310495   Completed

In [55]:
##75 Calculate the time spent in ED Department for each visit.df = pd.read_excel("HospitalDatabase .xlsx",sheet_name="EDVisits")
df = pd.read_excel("HospitalDatabase .xlsx",sheet_name="EDVisits")
a = df["EDDischargeTime"]
b = df["VisitDate"]
# returns a timedelta object
c = a-b

#Visit = df.groupby("EDVisitID")
print('Time spent for each visit: ', c)
#c.head()

Time spent for each visit:  0      0 days 11:20:22.924000
1      0 days 23:14:20.215000
2      0 days 01:50:56.151000
3      0 days 01:20:09.793000
4      0 days 02:38:20.043000
                ...          
1194   0 days 15:53:09.453000
1195   0 days 22:27:04.030000
1196   0 days 04:30:03.545000
1197   0 days 06:10:35.054000
1198   0 days 10:49:26.581000
Length: 1199, dtype: timedelta64[ns]


In [67]:
##54.Mortality O.E
#Create a calculated field” Observed Mortality” - COUNT(IF [Discharge Disposition] ='Expired’ THEN 1 END)
#Create another calculated field “O: E Mortality”- ([Observed Mortality])/SUM([Expected Mortality]) 
readmregistry = pd.read_excel("HospitalDatabase .xlsx",sheet_name="ReAdmissionRegistry")
df_readm = readmregistry[["DischargeDisposition"]]
df_mort = (df_readm == 'Expired').sum()
df_exp = readmregistry["ExpectedMortality"].sum().round(2)
df_exp
MortalityOE = ((df_mort/df_exp)*100)
display(MortalityOE)

DischargeDisposition    42.726264
dtype: float64

In [71]:
# ExtraQ 1: From question 34 Array: Extract individual 1D slices from main array and then combine them to form a 2D array 
#using numpy.ix_()
a = np.arange(1,31).reshape((6, 5))
print(a)
b = a[np.ix_([0,2],[1,3])]
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 2  4]
 [12 14]]


In [74]:
#ExtraQ 2: From question 34 Array:Removing the start, end elements of the given multidimensional array
a = np.arange(1,31).reshape((6, 5))
print(a)
print(a[:, 1:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]]
